.\" Manpage for eq4moc.
.\" Contact canu.conde@gmail.com to correct errors or typos.
.TH man 1 "2025" "1.1.1" "eq4moc man page"
.SH NAME
eq4moc - EQ for MOC
.SH SYNOPSIS
eq4moc [OPTIONS]
.SH DESCRIPTION
EQ for Moc is a terminal application to visualize and edit EQSET equalization files used by MoC (Music on Console).
.SH OPTIONS
.TP
\fB\-T\fP \fITHEME\fP, \fB\-\-theme\fP \fITHEME\fP
Use a theme file. The file will be searched in \fB/usr/share/moc/themes/\fP and in \fB~/.moc/themes/\fP.
.LP
.TP
\fB\-v\fP, \fB\-\-version\fP
Print the program version and exit.
.LP
.SH ENVIRONMENT VARIABLES
.TP
.B HOME
Tells eq4moc where your home directory is located and is used for various purposes, including the default location of the MOC directory.
.LP
.SH FILES
.TP
.B ~/.moc/eqsets/EQ_4_MOC
Default file to store equalization configuration. It is also the directory where eq4moc will search for other EQSET files.
.LP
.TP
.B ~/.moc/config
If this file exists, eq4moc will try to load the selected mocp theme from it.
.LP
.SH SEE ALSO
mocp(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Sebastián Bergara Conde (canu.conde@gmail.com)
